### ISSUE TITLE
For non-video downloading cases, disable the youtube-dl relative operations.

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#102]
Hi,

The youtube-dl is dedicated for video downloading, while PyIDM is aimed to be a general downloader. So for non-video downloading cases, the  youtube-dl relative operations should be disabled. But it seems I still can see some info log reported by youtube-dl even I'm downloading a iso image file. See the following for more info:

```
>> [generic] texlive2020-20200406: Downloading webpage
>> URL could be a direct video link, returning it as such.
>> youtube func: missing formats, re-downloading webpage
>> [generic] texlive2020-20200406: Requesting header
>> Could not send HEAD request to http://mirrors.ctan.org/systems/texlive/Images/texlive2020-20200406.iso: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'mirror-hk.koddos.net'. (_ssl.c:1108)>
>> [generic] texlive2020-20200406: Downloading webpage
>> Falling back on generic information extractor.
>> URL could be a direct video link, returning it as such.
>> youtube_func()> error: 'formats'

```

Regards

**Comment by pyIDM** [comment]
This something that bugging me a lot, I should only fire youtube-dl if the link is for a media stream or an html content
and avoid direct download like applications, iso, or any direct file download

the only thing that i can depend on right now is the "content-type" supplied by the remote server in its response headers,
still i think this option is not reliable enough, since servers are messy and most of the time doesn't respect protocol, and response headers might have wrong "content-type" 

Anyhow I will try to find more reliable solution to this issue

**Comment by hongyi-zhao** [comment]
If so, you can try to use the following method after the connection has been successfully established:   based on the power of youtube-dl, run it once to check the file type and then do the corresponding operations. 

I'm not sure whether this idea is appropriate.

Regards
