### ISSUE TITLE
Does PyIDM based on libcurl-multi or not?

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#112]
I greped the source code of PyIDM with `(lib)curl-multi` and find nothing. Doesn't PyIDM  based on [libcurl-multi](https://curl.haxx.se/libcurl/c/libcurl-multi.html)?

**Comment by pyIDM** [comment]
No, it based on individual  curl-easy handles

Initiated as pycurl.Curl()
One for every connection/ worker
Every handle will be initiated independently from a single thread and it will be re-used again with other segments once it is free

**Comment by hongyi-zhao** [comment]
Whether curl-multi will be more efficient considering that it's an official implementation for multi-threading and has completed many iterations/bug fixes?

**Comment by pyIDM** [comment]
I already tried curl Multi, i like the idea that I don’t have to fire threads myself because Multi is running all easy handle from current thread it will save memory and cpu time
Plus curl.Multi.perform()  is not blocking 

But i didn’t find a reliable method  to identify the finished handles to re-use them again

As I remember i can get info about finished handles only by calling multi.get_info() as I remembered but unfortunately it didn’t report all finished handles

Still have the code around, will have a look again, i might find something

**Comment by hongyi-zhao** [comment]
> I already tried curl Multi, i like the idea that I don’t have to fire threads myself because Multi is running all easy handle from current thread it will save memory and cpu time
> Plus curl.Multi.perform() is not blocking
> 
> But i didn’t find a reliable method to identify the finished handles to re-use them again
> 
> As I remember i can get info about finished handles only by calling multi.get_info() as I remembered but unfortunately it didn’t report all finished handles
> 
> Still have the code around, will have a look again, i might find something

Why not discuss your idea and difficulties | problems on its list?

**Comment by pyIDM** [comment]
> Why not discuss your above idea and (difficulties|problems) on (lib)curl list? I think your above problem should be not so difficult to solve considering that libcurl's objectives.

I will give it one more try before reporting to them
