### ISSUE TITLE
can't be run

### ISSUE THREAD

**Issue by mx202** [pyIDM/PyIDM#116]
Hello

it's really nice to see you software on github

but I couldn't run it because I got this message
`File "setup.py", line 19
    with open(f"{current_directory}/pyidm/version.py") as f:
                                                    ^
SyntaxError: invalid syntax
`

I hope you help us with it

And thank you

**Comment by pyIDM** [comment]
@mx202 
hello
I believe the python version you're running does't recognize f-string, you need python version 3.6+
what is your python version?

**Comment by mx202** [comment]
`~$ python --version
Python 2.7.18rc1
~$ python3 -V
Python 3.8.2
`

**Comment by pyIDM** [comment]
did you try the command using python3
i.e.
`python3 setup.py install`

or if you have pip installed and want to install from PyPi you can try
`python3 -m pip install pyidm`

**Comment by mx202** [comment]
I struggled so hard to make it work and in the end I succeeded with difficulty and tried it and it was a nice program even though the download speed is a little low and needs to be developed

Please help you by providing a copy of the program in the format `.deb` and `.flatpak` to make the installation process easy and fast, especially for non-developers

I also advise you to continue developing PyIDM because I strongly believe that it will be the elite download software
Trust me because I am sure

Last thing, The GUi of PyIDM is repellent. So, I recommend taking advantage of GUI of this project
https://github.com/salemebo/Ariafx

Please use this GUI. It will be the best ever

**Comment by pyIDM** [comment]
@mx202 
great it works for you

> the download speed is a little low and needs to be developed

one of the strength points in PyIDM is high download speed, please let me know did you test download speed, because sometimes the server "hosting the file you want to download", might limit bandwidth, so it is important to compare PyIDM with other download managers like "wget" or anything else available on your machine


> Please help you by providing a copy of the program in the format .deb and .flatpak to make the installation process easy and fast, especially for non-developers

Totally agree, there is already a plan to make a Flatpak, which is requested before in issue #79 

> Last thing, The GUi of PyIDM is repellent. So, I recommend taking advantage of GUI of this project
https://github.com/salemebo/Ariafx

PyIDM's current GUI might need some enhancements, 
I took a quick look to the gui you mentioned, it is nice but too much,  i prefer to keep the design as simple as possible, after all the goal is to download files.
