### ISSUE TITLE
Support for mitele.es

### ISSUE THREAD

**Issue by antonio8909** [pyIDM/PyIDM#153]
Hello

I would like to ask support for Mitele.es

Example link: https://www.mitele.es/series-online/la-que-se-avecina/temporada-4/capitulo-53-40_1006361575441/player/

Thanks in advance

**Comment by pyIDM** [comment]
@antonio8909 
currently pyidm depend on youtube-dl to extract video links from websites and doesn't have its own extractor,
kindly open an issue at https://github.com/ytdl-org/youtube-dl to ask support for Mitele.es

**Comment by antonio8909** [comment]
> @antonio8909
> currently pyidm depend on youtube-dl to extract video links from websites and doesn't have its own extractor,
> kindly open an issue at https://github.com/ytdl-org/youtube-dl to ask support for Mitele.es

Hello,

Please check https://ytdl-org.github.io/youtube-dl/supportedsites.html

It says it is supported @pyIDM

**Comment by pyIDM** [comment]
hello @antonio8909 
i tried the above link and it gives me error
also i can't play the video because it needs registration

if you have youtube-dl installed can you check this in terminal:

`
youtube-dl -F -v "https://www.mitele.es/series-online/la-que-se-avecina/temporada-4/capitulo-53-40_1006361575441/player/"

`
also you can try to add username and password in pyidm (settings>Network>Websit Auth) and try to check the link again
