### ISSUE TITLE
Add ability to select which videos to download from a playlist

### ISSUE THREAD

**Issue by raelb** [pyIDM/pyIDM#17]
Hi,
Thanks for your useful application.
It would be helpful if you can add the ability to select which videos to download from a playlist.
Thanks

**Comment by pyIDM** [comment]
I am glad you found this application useful, 
Nice suggestion :+1: , for sure it will be a good feature to add
I will start working on it and let you know once it finished

**Comment by raelb** [comment]
Great

**Comment by pyIDM** [comment]
Hello @raelb , I've done some quick code and added this feature in last update on github  "ability to choose which videos to include/exclude in playlist…,"
you can download the latest code by clone or download repository., exe releases still not updated yet

by the way, are you running from source code i.e pyIDM.py or from an exe release?

I didn't test this feature enough so please report any bug you might find.

![Screenshot_20191231_043515](https://user-images.githubusercontent.com/58998813/71608084-13251c80-2b87-11ea-8fed-10890b5dee24.png)

**Comment by raelb** [comment]
Hi PyIDM, That looks great. I am using the exe version. Is it possible to output an exe release? You could post it here. Then I will do some testing...
I also had another request. I will make another issue for that.
Thanks

**Comment by pyIDM** [comment]
Hello @raelb 
I uploaded an exe release version 3.7.1 at [latest version](https://github.com/pyIDM/pyIDM/releases/latest)
direct download  link [here](https://github.com/pyIDM/pyIDM/releases/download/v3.7.1.0/pyIDM_3.7.1.0_win64_cx.zip)

let me know if you faces any issues or bugs

**Comment by raelb** [comment]
Thanks.

Here is one issue I noticed:
![image](https://user-images.githubusercontent.com/13108198/71626860-f117b280-2bf7-11ea-9b5c-d98a585c915c.png)

I'm wondering why the default selected download format is different for different videos. (I am assuming they all have the same download formats available, since they are made by the same author in the same series)

Here is the playlist url I was using:
https://www.youtube.com/playlist?list=PLillGF-RfqbYhQsN5WMXy6VsDMKGadrJ-

Also, on Windows the checkbox looks like it is disabled. I wonder if this can be changed to show white...

**Comment by PySimpleGUI** [comment]
Changing the checkbox background isn't something currently exposed by PySimpleGUI.  The checkbox background is non-white because the check itself is white.  The color is changed to match the chosen color theme.

I do see a possible change though that could work out well.  Rather than it matching the background (which I've never liked BTW), PySimpleGUI can use the same techniques it uses for Tabs, Table headers, etc, which is to use the input colors.  I'll make a change and see how it looks.

**Comment by pyIDM** [comment]
@PySimpleGUI 
Thanks for quick response 👍

**Comment by pyIDM** [comment]
@raelb 
This is weird behaviour, I will have a look and see why this is happenning

**Comment by pyIDM** [comment]
@raelb 
fixed the problem of random video qualities, now all videos will have a default of 720p-mp4 "if available", ofcourse you can choose higher available qualities,
by the way you can change all videos quality at once from top combo-box.

v3.7.2 exe released at https://github.com/pyIDM/pyIDM/releases/latest give it a test and let me know if it works properly

![image](https://user-images.githubusercontent.com/58998813/71631345-d867c680-2c10-11ea-9e96-8a339ca5032d.png)

**Comment by PySimpleGUI** [comment]
While you're grabbing new PySimpleGUI versions and testing them, get the next version from GitHub and see if the checkbox and radio button background color is OK to you.

It's slightly lighter or slightly darker than the background.  Hopefully it's enough to show there's a box there but not enough for it to look strange.  It's meant to be subtle.

This example is for the "Dark Red" theme

![image](https://user-images.githubusercontent.com/46163555/71636831-f8dd5400-2c03-11ea-9da4-2b2f6fd0e4dc.png)

**Comment by PySimpleGUI** [comment]
Oh wait, I see you're using an old theme which uses named colors so it won't work for it.

I'll convert the themes to use hex colors instead of 'black' and 'white'.

You're using DarkBrown2
```python
                       'DarkBrown2': {'BACKGROUND': '#280001',
                                      'TEXT': 'white',
                                      'INPUT': '#d8d584',
                                      'TEXT_INPUT': 'black',
                                      'SCROLL': '#763e00',
                                      'BUTTON': ('black', '#daad28'),
                                      'PROGRESS': DEFAULT_PROGRESS_BAR_COLOR,
                                      'BORDER': 1,
                                      'SLIDER_DEPTH': 0,
                                      'PROGRESS_DEPTH': 0},
```

I'll be back....

**Comment by PySimpleGUI** [comment]
For something so dark, it's not going to look much different being darker.... this is what I've got working at the moment for Dark Brown 2

![image](https://user-images.githubusercontent.com/46163555/71637008-8ec6ae00-2c07-11ea-8acf-fb0ed3ab7306.png)

Believe it or not there is a difference.

For situations where the color scheme is lighter, I make the backgrounds lighter instead of darker.

Light Green 6 looks like this

![image](https://user-images.githubusercontent.com/46163555/71637017-bb7ac580-2c07-11ea-9455-ba5ee4592e96.png)

And finally here's the default color theme of Dark Blue 3.

![image](https://user-images.githubusercontent.com/46163555/71637023-dd744800-2c07-11ea-96a6-c2ae8b564ed5.png)

I'll check this in and see how it goes with users.

**Comment by pyIDM** [comment]
What about making checkbox color lighter all the time “Mainly white mixed with a vry little color of window background” no matter darker or lighter theme applied

**Comment by PySimpleGUI** [comment]
Because the color of the mark in the checkbox is not under my control.  It is the SAME as the text for the checkbox and radio button.

The only thing I can change is the box background.

Some of the themes this will cause the indicator to disappear entirely as the contrast is already low on a few.  I dunno if that makes sense or not. 

The result of the new coloring is that the checkmark is more noticable not less.  If it's a white checkmark, then the box is made darker.  If the charkmark is dark, then the box is made lighter.  It's a guaranteed easier to see rather than a guaranteed more difficult to see.

**Comment by pyIDM** [comment]
oh! I understand now
