### ISSUE TITLE
YouTube playlist don't work

### ISSUE THREAD

**Issue by Miragide** [pyIDM/PyIDM#190]
Hello,
YouTube playlist dl don't work.
When i enter an url playlist...
ex: https://www.youtube.com/playlist?list=PLwvr71r_LHEXwKxel0_hECnTb75JHEwlf
I get this:
![image](https://user-images.githubusercontent.com/15331478/99267996-e8869580-2824-11eb-868e-712fc6f67638.png)
How to dowload youtube playlist videos please?
Thanks :)

**Comment by pyIDM** [comment]
@Miragide 
This is because youtube-dl needs to be updated
go to settings tab update section and switch to  "youtube-dlc" instead of youtube-dl and wait until version number shows up infront of youtube-dlc  like screenshot below

![image](https://user-images.githubusercontent.com/58998813/99297573-200b3700-2851-11eb-8aa6-7061bf3f9ac5.png)


a popup will show up like below to indicate a new version

![image](https://user-images.githubusercontent.com/58998813/99297748-59dc3d80-2851-11eb-9023-685c0e51b029.png)


press ok and keep watching the log until update finish, 
if you are running exe version on windows you will get a popup like below when update finished
![image](https://user-images.githubusercontent.com/58998813/99297869-85f7be80-2851-11eb-91a4-227fe481ae9e.png)


then restart pyidm and try your link again

This is the results after update
![image](https://user-images.githubusercontent.com/58998813/99296965-3ebcfe00-2850-11eb-94ae-920707fff4e1.png)

**Comment by Miragide** [comment]
Great! Thank you!! :)
