### ISSUE TITLE
Make PyIDM start at Windows startup and...

### ISSUE THREAD

**Issue by Dhyfer1** [pyIDM/PyIDM#196]
Hi Dev.

I am using the portable version of PyIDM but I see that there is no option for PyIDM to run at Windows startup, so I would like to see that function in the next update.

I would also like PyIDM to be able to download torrent files, if possible.

Thanks in advanced.

**Comment by pyIDM** [comment]
@Dhyfer1 
Thanks for suggestions

> option for PyIDM to run at Windows startup

personally i don't prefer any applications to run at windows startup, because it make windows take longer time 
in case you need this feature, there is already a way to add any app to windows startup 
https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd

> I would also like PyIDM to be able to download torrent files, if possible.

The main target of this application is to download videos from various streaming website "same as youtube-dl does but with higher speeds", and because it uses curl as a download engine it can download normal files too.
adding a torrent support will add extra complexity to this application, where there is already dozens of professional torrent clients available for free
so there is no plan to add support for torrents

**Comment by Dhyfer1** [comment]
> personally i don't prefer any applications to run at windows startup, because it make windows take longer time
> in case you need this feature, there is already a way to add any app to windows startup
> https://support.microsoft.com/en-us/windows/add-an-app-to-run-automatically-at-startup-in-windows-10-150da165-dcd9-7230-517b-cf3c295d89dd
> 

Yes, I know that too. But what I mean is that this option exists not as an option activated by default, but as a box where you check or uncheck that function. What do you say?
