### ISSUE TITLE
Why PyIDM needs both youtube_dl and youtube_dlc?

### ISSUE THREAD

**Issue by hongyi-zhao** [pyIDM/PyIDM#206]
I noticed that the following required pkgs list of PyIDM:

`['plyer', 'certifi', 'youtube_dl', 'youtube_dlc', 'pycurl', 'PIL', 'pystray', 'awesometkinter']`

But I am confused why PyIDM needs both [youtube-dl](https://github.com/ytdl-org/youtube-dl) and [youtube-dlc](https://github.com/blackjack4494/yt-dlc). Any hints will be highly appreciated.

Regards,
HY

**Comment by pyIDM** [comment]
@hongyi-zhao 
2 months ago youtube-dl project has been shutdown on github, that's why youtube-dlc is used
now youtube-dl come back to life on github, so it is not a bad idea to keep both engines and user can switch between them from settings

for more info on why github removed youtube-dl https://www.eff.org/ar/deeplinks/2020/11/github-reinstates-youtube-dl-after-riaas-abuse-dmca 

![image](https://user-images.githubusercontent.com/58998813/103763676-0bd0f400-4fcf-11eb-8759-441464366984.png)

**Comment by hongyi-zhao** [comment]
Thank you very much for letting me know about this.
