### ISSUE TITLE
YouTube links not reconized (SSL problem)

### ISSUE THREAD

**Issue by subnut** [pyIDM/PyIDM#213]
Using Latest Released AppImage on Linux
```
>> get_headers()> getting headers for: https://www.youtube.com/watch?v=Sk9TatW9ino
>> Segments-watch.htm, (1): ['0:None']
>> headers: {'content-type': 'text/html; charset=utf-8', 'x-content-type-options': 'nosniff', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': 'mon, 01 jan 1990 00:00:00 gmt', 'date': 'tue, 02 feb 2021 13:15:59 gmt', 'x-frame-options': 'sameorigin', 'strict-transport-security': 'max-age=31536000', 'p3p': 'cp="this is not a p3p policy! see http://support.google.com/accounts/answer/151657?hl=en for more info."', 'server': 'esf', 'x-xss-protection': '0', 'set-cookie': 'visitor_info1_live=12e8sxdqstk; domain=.youtube.com; expires=sun, 01-aug-2021 13:15:59 gmt; path=/; secure; httponly; samesite=none', 'alt-svc': 'h3-29=":443"; ma=2592000,h3-t051=":443"; ma=2592000,h3-q050=":443"; ma=2592000,h3-q046=":443"; ma=2592000,h3-q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'accept-ranges': 'none', 'vary': 'accept-encoding', 'transfer-encoding': 'chunked', 'status_code': 200, 'eff_url': 'https://www.youtube.com/watch?v=Sk9TatW9ino'}
playlist here
>> start create video playlist
>> [youtube] Sk9TatW9ino: Downloading webpage
>> ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))
>> controller._create_video_playlist()> No streams found
>> get_headers()> getting headers for: https://www.youtube.com/watch?v=Sk9TatW9ino
>> Segments-watch.htm, (1): ['0:None']
>> headers: {'content-type': 'text/html; charset=utf-8', 'x-content-type-options': 'nosniff', 'cache-control': 'no-cache, no-store, max-age=0, must-revalidate', 'pragma': 'no-cache', 'expires': 'mon, 01 jan 1990 00:00:00 gmt', 'date': 'tue, 02 feb 2021 13:17:21 gmt', 'x-frame-options': 'sameorigin', 'strict-transport-security': 'max-age=31536000', 'p3p': 'cp="this is not a p3p policy! see http://support.google.com/accounts/answer/151657?hl=en for more info."', 'server': 'esf', 'x-xss-protection': '0', 'set-cookie': 'visitor_info1_live=4nt5llj_geo; domain=.youtube.com; expires=sun, 01-aug-2021 13:17:21 gmt; path=/; secure; httponly; samesite=none', 'alt-svc': 'h3-29=":443"; ma=2592000,h3-t051=":443"; ma=2592000,h3-q050=":443"; ma=2592000,h3-q046=":443"; ma=2592000,h3-q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"', 'accept-ranges': 'none', 'vary': 'accept-encoding', 'transfer-encoding': 'chunked', 'status_code': 200, 'eff_url': 'https://www.youtube.com/watch?v=Sk9TatW9ino'}
playlist here
>> start create video playlist
>> [youtube] Sk9TatW9ino: Downloading webpage
>> ERROR: Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)> (caused by URLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))
>> controller._create_video_playlist()> No streams found

```

**Comment by pyIDM** [comment]
@subnut 
Thanks for reporting
it looks like AppImage needs ssl certificates update, will work on a fix for this

i can verify running ok from source:
![image](https://user-images.githubusercontent.com/58998813/106611141-46975f00-6570-11eb-96f6-52f2034c959c.png)

**Comment by pyIDM** [comment]
@subnut 
for a temporarily workaround you can disable ssl verification by un-checking option at 
Settings>Network>verify server's ssl certificate

Then restart PyIDM and it will work normally

![image](https://user-images.githubusercontent.com/58998813/106773002-41f2a980-6649-11eb-8384-6d737e49f960.png)

**Comment by pyIDM** [comment]
Problem fixed by pointing to 'cacert.pem' file in certifi package
added this environmental variable:
```
# set ssl certificate
SSL_CERT_FILE: '${APPDIR}/usr/lib/python3.6/site-packages/certifi/cacert.pem'
```


Full explanation of the root cause at:
https://gitlab.com/probono/platformissues#certificates

as quoted below:
---
Certificates:
Should be installed to a standard location that is the same in all distributions. Currently this is not the case and where certificates go is apparently entirely random by distribution, as of mid-2017:
```
"/etc/ssl/certs/ca-certificates.crt",                // Debian/Ubuntu/Gentoo etc.
"/etc/pki/tls/certs/ca-bundle.crt",                  // Fedora/RHEL
"/etc/ssl/ca-bundle.pem",                            // OpenSUSE
"/etc/pki/tls/cacert.pem",                           // OpenELEC
"/etc/ssl/certs",                                    // SLES10/SLES11, https://golang.org/issue/12139
"/usr/share/ca-certs/.prebuilt-store/",              // Clear Linux OS; https://github.com/knapsu/plex-media-player-appimage/issues/17#issuecomment-437710032
"/system/etc/security/cacerts",                      // Android
"/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem", // CentOS/RHEL 7
"/etc/ssl/cert.pem",                                 // Alpine Linux
```
Source: https://serverfault.com/questions/62496/ssl-certificate-location-on-unix-linux
The result is that if we bundle something like libgnutls, then it fails to find the certificates if the target system happens to store them in a different place.
Workaround:
Patch whatever consumes certificates (e.g., libgnutls) to look in all known places. Example: https://github.com/darealshinji/vlc-AppImage/issues/1#issuecomment-321041496
Update: Can SSL_CERT_FILE and/or SSL_CERT_DIR be used to point to the location of the certificates?
According to the documentation,

`Alternatively the SSL_CERT_DIR environment variable can be defined to override this location. The default CA certificates file is called cert.pem in the default OpenSSL directory. Alternatively the SSL_CERT_FILE environment variable can be defined to override this location.`

In this case, we would need to check all possible locations where the different distributions tend to place those files, and then export the one where they have actually be found, prior to launching the payload executable.
More information:

https://www.happyassassin.net/2015/01/12/a-note-about-ssltls-trusted-certificate-stores-and-platforms/

https://github.com/openssl/openssl/issues/7481#issuecomment-583719914 (SSL_CERT_FILE and SSL_CERT_DIR)

**Comment by pyIDM** [comment]
@subnut 
New AppImage release with a fix at https://github.com/pyIDM/PyIDM/releases/latest
