### ISSUE TITLE
Order of items in file format dropdown

### ISSUE THREAD

**Issue by raelb** [pyIDM/pyIDM#25]
Btw, what is "normal"?

This is perhaps a matter of personal preference, however I find it quite difficult to sift through the values in the dropdown:

![image](https://user-images.githubusercontent.com/13108198/71633927-2cc67280-2c20-11ea-9a16-9632a5ddbe18.png)

For me, the question is:
1 -> what format do I want to download in,
2 -> what quality do I want

With this is mind, it would be easier (for me...) if formats were grouped together by file type, and then format quality.

mp4  ....1080
mp4 ... 720
mp4...
webm
webm
etc..

Also, it would be nice if there could be a dividing line between the different file formats to make distinguishing between them easier. Or perhaps group together by indent, e.g.:

mp4
.... mp4 1080
.... mp4 720
webm
.... webm ....
etc..

Also, I think the "1280x720" detail part is unnecessary to display, and makes sifting through the info more difficult.

Thanks!

**Comment by pyIDM** [comment]
Youtube usually sends streams in 3 types:
- Normal videos: I mean by normal a video file which has an audio, marked "normal" in quality menu.
- Dash Videos: a video file with no sound / audio, which marked by "video" in quality menu
- Audio : an audio only file, marked "audio" in quality menu

Technically:
Downloading "normal" video is straight forward like any other file, but when you decide to download a Dash video  you will end up with a video file with no audio, that's why the application will download an audio file then merge it with this Dash video to produce a normal video file.

However The available streams are different for every video, still making a defined list can be done
will add it to my TODO list

thanks again and keep those suggestions coming! :+1:

**Comment by pyIDM** [comment]
Added new design for stream menu, new release build v4.0.0 available at https://github.com/pyIDM/pyIDM/releases/latest

![screenshot](https://user-images.githubusercontent.com/58998813/71775067-10f60000-2f83-11ea-9ad4-2bbd3d6916e6.png)

**Comment by raelb** [comment]
That looks great. Thanks.
However, why are there 2 values for some quality (i.e 720, 360)?
If because some are "normal" then perhaps some indication after the text e.g. (normal) / (n) / (*).
How is 360 so big (12.2MB), almost the same as 720 (13.8MB/11.1MB)?

**Comment by pyIDM** [comment]
I noticed also some repeated qualities which is not right, they should be unique values,
I will check my messy code and see what happened
Thanks @raelb for this notice

**Comment by pyIDM** [comment]
Hello @raelb again,
I fixed the problem, as you said it is a different streams with same quality, example 360 normal and 360 dash with different sizes, so I selected the normal streams if available and select dash stream if quality doesn't exist in normal ones

> How is 360 so big (12.2MB), almost the same as 720 (13.8MB/11.1MB)?

when i checked I found out that 360 stream is "normal" with embedded sound but the 720 is "dash" a video with no sound, and I believe the audio file will almost around 5 MB, you will notice this in small sized files only

I added new exe v4.1.0 with mentioned fix https://github.com/pyIDM/pyIDM/releases/latest
