### ISSUE TITLE
error loading requirements.txt

### ISSUE THREAD

**Issue by yochananmarqos** [pyIDM/pyIDM#31]
It should be looking in `/usr/lib/python3.8/site-packages/pyidm/` I would imagine, but the file isn't there either.

```
error loading requirements.txt [Errno 2] No such file or directory: '/usr/lib/python3.8/site-packages/requirements.txt'
falling back to requirements listed in dependency.py
```

**Comment by pyIDM** [comment]
@yochananmarqos 
i ignored to include the requirements.txt in pypi release since it is already encoded in setup.py and pip will install the requirements automatically 

Still I prefer to include it, will correct it in next release
Thanks for reporting 👍

**Comment by yochananmarqos** [comment]
It does it in both the GitHub and PyPI release. I'm actually installing it via my own [PKGBUILD](https://github.com/yochananmarqos/pkgbuilds/tree/master/pyidm) on Manjaro GNOME.

Also, the the `setup.py` is looking for `README.md` like on PyPI, while on GitHub it's `readme.md`.

**Comment by pyIDM** [comment]
Oh! I should have a look and check these points you mentioned

**Comment by pyIDM** [comment]
@yochananmarqos 
changed readme.md to README.md on github
for pypi release I am unable to include requirements.txt into pypi package without using complicated code since it is outside the package folder, if you find an easy way please let me know

then I decided to silent the error of not finding requirements.txt in dependency.py file since it is harmless
