### ISSUE TITLE
Downloads get stuck

### ISSUE THREAD

**Issue by smaragdus** [pyIDM/pyIDM#61]
Using [pyIDM](https://github.com/pyIDM/pyIDM) version [2020.3.20](https://github.com/pyIDM/pyIDM/releases/tag/2020.3.20) I experience a problem, the downloads stop usually over 90%, screens:

![pyIDM 2020 03 20 - 2020-03-23 - 013](https://user-images.githubusercontent.com/9025757/77283688-a62ca900-6cd5-11ea-9140-7fbecd85c63b.png)

![pyIDM 2020 03 20 - 2020-03-23 - 018](https://user-images.githubusercontent.com/9025757/77283704-afb61100-6cd5-11ea-8453-a1743fb57839.png)

and never complete. However when I execute command 'Stop All' and then 'Resume All' the downloads finish successfully almost immediately.

I wonder whether this problem is reproducible or it is a network problem on my side.

You may consider adding two new buttons:

- Resume
- Stop

which resume the selected download and respectively stop the selected download. For me stopping and resuming individual downloads would be better than stopping and resuming all downloads (even the completed ones).

**Comment by pyIDM** [comment]
@smaragdus 
please restart PyIDM and try this download again until it stuck, then do the same  'Stop All' and then 'Resume All' until the download finishs successfully 
then send log.txt in PyIDM folder, it might contains where the problem is

or if you can paste url here and i will try it and see if the problem persist

> You may consider adding two new buttons:

you can select a download item and use the buttons on top "cancel" == stop, and you have "Resume"

**Comment by smaragdus** [comment]
@pyIDM 

Thanks for the quick response. The problem appeared again, I followed your advice and I will attach the log below:

[log.txt](https://github.com/pyIDM/pyIDM/files/4367550/log.txt)

I hope this will help you to investigate the problem.

Regards

**Comment by smaragdus** [comment]
@pyIDM 

I was so totally tired that I forgot about the upper tool bar and I didn't notice it either. Please excuse me, I didn't sleep tonight and I was doing some other things while testing the latest version. I was totally inadequate.

**Comment by pyIDM** [comment]
@smaragdus 
I tried the link you provided and it works without a problem,
and from the log i can see that PyIDM only used 2 connections only to download this file, I think this is because you set the segment size to a very high value, 
the normal segment size should be 512 kbytes or 1 MB

please set segment size to 512 KB and try again

![image](https://user-images.githubusercontent.com/58998813/77292257-99fe1700-6ce8-11ea-96d3-ab8578ed60e6.png)

by the way i did set segment value to a high value like 100 MB and PyIDM used only 2 connections same as yours, and experience a little download stuck at the end but after few seconds it completed successfully
most of the time youtube limit bandwidth by connection, thats why you get high download speeds with multiple connections

**Comment by smaragdus** [comment]
@pyIDM 

Thanks for responding and for offering solution. I did a new test and I was able to download two videos without any of the downloads getting stuck. Actually I haven't changed the default settings for segment size. As the problem did not reappear I will close this issue, Perhaps it was some kind of temporary local network issue.
