### ISSUE TITLE
[Bug] I cant update youtube-dl

### ISSUE THREAD

**Issue by Tox86** [pyIDM/pyIDM#63]
Hello, so i cant download youtube-dl and show xxx?
Scrolling dosen't work in settings 
Gif:

https://imgur.com/2v1VQEF

Log:
>> looking for video streams ... Please wait
>> youtube_func()> processing: https://www.youtube.com/watch?v=9ULfFe9_D1c
>> youtube-dl module still not loaded completely, please wait
>> looking for video streams ... Please wait
>> youtube_func()> processing: https://www.youtube.com/watch?v=9ULfFe9_D1c
>> youtube-dl module still not loaded completely, please wait

Cheers

**Comment by pyIDM** [comment]
@Tox86 
Thanks for reporting this issue
it looks like update function is broken, and your current PyIDM copy no longer working, please remove it and download a working copy again or if you still have zip copy of PyIDM you can unzip it and use it instead, and don't use this update button again since it will break the application until i fix it.



> Scrolling dosen't work in settings

Yes I am aware of this issue since setting page won't scroll with mouse wheel, there is a plan to change it's design

I will work on both issues and let you know once finished and  make new release

**Comment by pyIDM** [comment]
Done with new release 2020.3.31
new design for settings Tab at https://github.com/pyIDM/pyIDM/issues/13#issuecomment-607633667

![s1](https://user-images.githubusercontent.com/58998813/78214405-75a6f500-74b5-11ea-838f-c7ad95b722ed.PNG)

**Comment by Tox86** [comment]
Test

**Comment by Tox86** [comment]
![asdf](https://user-images.githubusercontent.com/7013508/78270570-5f169300-74e1-11ea-83e7-4e117f93f3f2.PNG)

👌👌👌👌
