### ISSUE TITLE
Ask user permission before checking for update

### ISSUE THREAD

**Issue by pyIDM** [pyIDM/PyIDM#76]
PyIDM does checks for new updates every 7 days by default, "could be changed from options to daily or every month", however there is 2 issues:

1- application checks for update if there is no previous checks done, i.e. no setting.cfg file, which means newly downloaded version will do non required check.

2- application should ask user permission to check for update.

IMPLEMENTATION:
1- no checks will be done if last checked date == 0, i.e. first run for app. with no setting.cfg file found.
2- Popup window to alert user and has check box for "don't show this message again" and buttons will be "Ok" and "Later".
if "Later" button chosen, PyIDM will scheduled next update after 7 days,

**Comment by smaragdus** [comment]
I would appreciate if there is an option to disable update check:

**Check for updates every day(s):**

- 1
- 7
- 30
- Never


 For these users who are following this project update check is not needed because these users receive notifications for new releases by mail. Personally I disable update check for any program when this is possible as I get notifications via mail and via RSS. I prefer update check on demand. Also I usually first test new releases before updating as sometimes there are critical bugs (for example- qBittorrent) which may make the latest releases unwanted.

**Comment by pyIDM** [comment]
@smaragdus 
I was expecting someone to ask for this, 

will add the option to disable check for update completely as user should have full control of the application, 
thanks for suggestions :+1:

**Comment by smaragdus** [comment]
@pyIDM 

I commented on this issue because you opened it. Actually in this case update checks are not plaguing me because I always use the latest version once it is released. For me this is a matter of principle as I always state that the users should be given the right to use software the way they like including an option to use a particular version. For example most modern browsers treat users like slaves, like sheeple and one has to use sophisticated methods to disable automatic update checks and automatic updates. I am glad that you understand user;s freedom the way I understand it. I am pleased to mention that in this particular case (pyIDM) there was no single update which would make me want to go back to an earlier version. I really appreciate your work in these hard times.

Regards

**Comment by pyIDM** [comment]
Thanks a lot @smaragdus :)
