### ISSUE TITLE
Nice job of using latest PySimpleGUI constructs

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#8]
Was impressed to see an evolution from the older PySimpleGUI constructs that existed when you started your project to the newest ways of doing things.  Some of them are not shown in demo code very often as to not confuse newcomers.

The Missing Packages GUI shows this extremely well with using all 3 of the most recent shortcuts.

1. Window['key'] instead of Window.find_element('key')
2. Directly Calling an element rather than calling update() -- window['key'](data)
3. Directly Calling the window rather than calling read() - window()

Really impressed at how much you've grown along with the GUI package you're using.

**Comment by PySimpleGUI** [comment]
Here's the code where I saw all this:
```python
    layout = [
        [sg.T(msg)],
        [sg.T('Installation status:')],
        [sg.Multiline('', key='missing_pkg_status', size=(50, 8), autoscroll=True)],
        [sg.Multiline('', key='log', size=(50, 8), autoscroll=True, )],
        [sg.B('Proceed', key='Proceed'), sg.Cancel()]
    ]

    window = sg.Window(title='Hanash ... Missing packages installation', layout=layout)
    while True:
        event, values = window()

        if event in (None, 'Cancel'):
            window.Close()
            exit() # quit application
        if event == 'Proceed':
            if not missing_packages:
                window.Close()
                break

            failed_packages = []
            for package_name in missing_packages[:]:
                done, log = install(package_name)
                window['missing_pkg_status'](f"{package_name} .......... {'Done' if done else 'Failed'} \n", append=True)
                window['log'](log, append=True)
                window.Refresh()

```

Oh, by the way, there are PEP8 bindings for everything now, so you can call lower case methods that are PEP8 compliant - window.close() rather than window.Close()

I'm sure you already know this and there's no real compelling reason to go through your code and change all the calls.

**Comment by Aboghazala** [comment]
No doubt PySimpleGUI has gone so far, with a lot of effort to make the easy easier and painless, i love to try new features you add to this project, 
PEP8 compliance using small case names was one of the biggest improvements to be more pythonic, it was confused to remember using the CamelCase naming and i used to get alot of errors because of forgetting to use upperCase names.

also i have to admit you already have done a great job in source code comments, which make it super easy to understand the source code,  still The remaining thing which i wish to see is the documentation structures is not easy to find what you're looking for so i have to go thru the source code to figure out what to do,

example if I need to check Multiline() widget, i should able to navigate thru the docs tree and get Multiline() section and get information on how to use it with a simple use case, listing all available arguments, it will be better for new comers and experience users also.

All in all, great job you are doing, i do see your passion of your project in your code, keep going 👍 👍

**Comment by PySimpleGUI** [comment]
Are you looking at the main documentation?  It's indexed so you can easily find the sections on each element
https://pysimplegui.readthedocs.io/en/latest/#multiline-element_1

That's the call summary section at the end that details every parameter to every method.

Then there's the section with a use case and demo code.

https://pysimplegui.readthedocs.io/en/latest/#multiline-element

Both of the things you've asked for in documentation form are right there in the 500+ pages of documentation (indexed on the left side).

HINT - press control+F on the main docs page and type what you're looking for.  There aren't THAT many places that usually come up.  Again, check the table of contents on the left.

Maybe it's been a while since you saw the docs?

**Comment by Aboghazala** [comment]
Sorry, This is my bad, i thought this wasn't there, it is well documented, great job your doing there

**Comment by PySimpleGUI** [comment]
Thank you!  I'm glad you found the docs are up to the standards you were looking for.  That's a relief!  They are continuously being updated so when in doubt, it doesn't hurt to look there again.  I usually simply search using Control+F from the docs page at http://www.PySimpleGUI.org. That gets me at least to the part of the table of contents on the left that's a match.
