### ISSUE TITLE
HUGE repository!

### ISSUE THREAD

**Issue by PySimpleGUI** [pyIDM/pyIDM#9]
I'm struggling to close your repository.  Not all of us have "high speed".  I'm not even at 40% cloned and I'm at 110 MB.

It downloaded a .pack file in the folder .git\objects that is over 150 MB.

I definitely wouldn't be mixing EXEs and in with your source code.  Maybe make it part of the PyPI release?  I'm not sure how to handle it.  You're also going to get privacy nuts and non-window people fleeing, not wanting a foreign EXE file to be downloaded onto their system.

I'm not sure how I would go about distributing an end user application using Python, but I don't think I would do it by having one repository.   Most GitHub users are going to be there for the source.  It's the PyPI people that would maybe go for an EXE.  It's how I've seen other exe's packaged.  This way someone simply pip installs your EXE.

I'm not exactly sure what's up with the .pack file being there and so huge, but I have to think it has something to do with hosting a binary.

**Comment by Aboghazala** [comment]
This is weired, when i download the repo from github it download 36 MB, but size went up to 188 MB with git clone, I think because it download all commit history and the files which has been deleted in case of i want to revert a commit
anyhow, I already got a 'pyIDM' user name in github and i will transfer the repo to pyIDM/pyIDM, but first i need to clean all this mess in .git history.
then i think i can make another project to host binaries i.e. pyIDM/binaries, so it won't interfere with main repo source code, 
thanks for drawing my attention to this issue,
