### ISSUE TITLE
set segment size dynamically

### ISSUE THREAD

**Issue by pyIDM** [pyIDM/PyIDM#97]
small segment size like 512 KB doesn't fit into faster network connection, on other side bigger segment size affect speed on average network speeds 

refer to issue  #93

need to set segment size dynamically to get max network speed

**Comment by hongyi-zhao** [comment]
To be more efficient, the dynamic segmentation should be implemented in real-time segment-size adjustable manner during the whole downloading progress.

**Comment by hongyi-zhao** [comment]
Some complementary on technical descriptions for the implementation of dynamic segmentation.

[Flareget](https://flareget.com/):

**Amazingly Fast Downloads!**

It uses a robust in-place dynamic file segmentation algorithm to speed up the download. The download is split into segments to increase the speed.


[xdm](https://subhra74.github.io/xdm/):

**Download 5 time faster**

XDM can accelerate downloads by up to 5 times due to its intelligent dynamic file segmentation technology. Unlike other download managers and accelerators XDM segments downloaded files dynamically during download process and reuses available connections without additional connect and login stages to achieve best acceleration performance.

**Comment by pyIDM** [comment]
@hongyi-zhao 
Just added dynamic file segmentation feature to PyIDM, let me know if it works properly for you

**Comment by hongyi-zhao** [comment]
Great, what's specifications used by you? IDM/XDM/Flareget or mixed features of them?

**Comment by pyIDM** [comment]
I used closer technique to idm, 
a free worker will search for the biggest remaining segment and split remaining size in half to share the task with the current worker

**Comment by hongyi-zhao** [comment]
I tried with the following two cases and all the testings are for this [file](http://mirrors.ctan.org/systems/texlive/Images/texlive2020-20200406.iso).

1. Using a non-completed file downloaded by the previous version of pyidm which don't implement this feature. The ultimate file is corrupt and a mismatch md5sum.

2.  Starting a fresh downloading with the currently latest pyidm. It works and I noticed that the average downloading speed gains a significant increase.

As for other (problem|bug)s, I will open other separate issues for reporting them.

Regards,
HY
